name: 'Generic Kubernetes client (kubectl) with AWS cli'
description: 'GitHub Action for interacting with kubectl being possible to authenticate to an EKS cluster via aws cli'
author: 'Rodrigo P. Fraga <rodrigo.p.fraga@gmail.com>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  KUBE_CONFIG:
    description: 'Kubernetes configuration'
  KUBE_HOST:
    description: 'Kubernetes cluster host (IP only, without protocol)'
  KUBE_USERNAME:
    description: 'Kubernetes cluster username'
  KUBE_PASSWORD:
    description: 'Kubernetes cluster password'
  KUBE_CERTIFICATE:
    description: 'Cluster CA certificate'
  AWS_ACCESS_KEY_ID:
    description: 'AWS access key id'
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS secret key id'
runs:
  using: 'docker'
  image: 'Dockerfile'
